import os, re
from cubaCodeTemplate import *
from string import zfill

listdir = os.listdir('.')

pat = re.compile('.*func.*c$')
obj_src = [i for i in listdir if pat.match(i)]
num = len(obj_src)

### compile object files
for src in obj_src:
    Object(src)

### list of *.o-files
objs = [ s[:-1]+'o' for s in obj_src]

#tmpPath   = '/tmp'
localPath = os.getcwd() 
cubaPath  = os.path.expanduser('~')+"/cuba/Cuba-3.0"
headers   = [ os.path.join(localPath,s[:-1]+'h') for s in obj_src]

env = Environment(  LIBS=['m','cuba'], 
                    LIBPATH=cubaPath, CPPPATH=[cubaPath],
                    platform='posix',ENV=os.environ) 

includes,functions = [],[]

for i, fileName in enumerate(headers):
    functions += ["f = func_t_%d(xx);" % i]
    includes += ["#include \"%s\"\n"%(fileName)]

#cubaFiles = [os.path.join(tmpPath,localPath.split('/')[-1]+"_cuba__E%s.c" \
cubaFiles = [os.path.join(localPath,localPath.split('/')[-1]+"_cuba__E%s.c" \
        %zfill(i,len(str(num)))) for i in range(num)]
for i, cubaFile in enumerate(cubaFiles):
    f = open(cubaFile,'w')
    f.write(coreCubaCodeTemplate.format(
            includes = includes[i],
            cuba_path= os.path.join(cubaPath,'cuba.h'),
            functions= functions[i]))
    f.close()
    #print cubaFile+" created\n"
    print "Compiling", cubaFile
    targetName = "cuba__%s.run" %zfill(i,len(str(num)))
    env.Program(target = targetName, source = [cubaFile]+objs)
env.Clean(objs,'.')
