import os, re
from cubaCodeTemplate import *

listdir = os.listdir('.')

pat = re.compile('.*func.*c$')
obj_src = [i for i in listdir if pat.match(i)]

### compile object files
for src in obj_src:
    Object(src)

### list of *.o-files
objs = [ s[:-1]+'o' for s in obj_src]


localPath = os.getcwd() 
cubaPath  = "/home/kirienko/cuba/Cuba-3.0"
headers   = [ os.path.join(localPath,s[:-1]+'h') for s in obj_src]


includes,functions = "",""

for i, fileName in enumerate(headers):
    functions += "\n f += func_t_%d(xx);\n" % i
    includes += "#include \"%s\"\n"%(fileName)


cubaFile = os.path.join(localPath,localPath.split('/')[-1]+"_cuba__E0.c")
f = open(cubaFile,'w')
f.write(coreCubaCodeTemplate.format(
        includes = includes,
        cuba_path= os.path.join(cubaPath,'cuba.h'),
        functions= functions))
f.close()
print cubaFile+" created\n"
    
env = Environment(  LIBS=['m','cuba'], 
                    LIBPATH=cubaPath, CPPPATH=[cubaPath],
                    platform='posix',ENV=os.environ) 

print "Compiling", cubaFile
targetName = 'cuba.run'
env.Program(target = targetName, source = [cubaFile]+objs)
